import Image from "next/image"
import { Card, CardContent } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Clock } from "lucide-react"

// Mock AI-generated NFT examples
const aiExamples = [
  {
    id: 1,
    name: "Cosmic Neural #42",
    image: "/placeholder.svg?height=300&width=300",
    trend: "Abstract Neural",
    timeToCreate: "12 seconds",
    aiModel: "Trend Analyzer v2",
  },
  {
    id: 2,
    name: "Pixel Universe #17",
    image: "/placeholder.svg?height=300&width=300",
    trend: "Pixel Art",
    timeToCreate: "8 seconds",
    aiModel: "Pixel Generator v3",
  },
  {
    id: 3,
    name: "Neon Dreams #76",
    image: "/placeholder.svg?height=300&width=300",
    trend: "Cyberpunk",
    timeToCreate: "15 seconds",
    aiModel: "Neon Synthesizer v1",
  },
  {
    id: 4,
    name: "Data Flow #23",
    image: "/placeholder.svg?height=300&width=300",
    trend: "Data Visualization",
    timeToCreate: "10 seconds",
    aiModel: "Chain Visualizer v2",
  },
]

export function AiGeneratedExamples() {
  return (
    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
      {aiExamples.map((example) => (
        <Card key={example.id} className="overflow-hidden group">
          <CardContent className="p-0">
            <div className="relative">
              <Image
                src={example.image || "/placeholder.svg"}
                alt={example.name}
                width={300}
                height={300}
                className="w-full h-auto transition-transform group-hover:scale-105"
              />
              <div className="absolute top-2 right-2">
                <Badge className="bg-purple-600">{example.trend}</Badge>
              </div>
              <div className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/80 to-transparent p-4">
                <h3 className="font-medium text-white">{example.name}</h3>
                <div className="flex items-center mt-1">
                  <Clock className="h-3 w-3 text-gray-300 mr-1" />
                  <p className="text-xs text-gray-300">Created in {example.timeToCreate}</p>
                </div>
              </div>
            </div>
            <div className="p-3 bg-slate-50">
              <p className="text-xs text-slate-500">
                Generated by <span className="font-medium">{example.aiModel}</span>
              </p>
            </div>
          </CardContent>
        </Card>
      ))}
    </div>
  )
}

